{
  "_annotation": {
    "cve_id": "CVE-2024-24773",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-24773.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:apache:superset:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "794700D0-E335-5089-942C-353A8718D89F",
                "versionEndExcluding": "3.0.4",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:apache:superset:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "F95A2CC0-DB32-5A88-B45D-C001DD5D3E3B",
                "versionEndExcluding": "3.1.1",
                "versionStartIncluding": "3.1.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}