{
  "_annotation": {
    "cve_id": "CVE-2024-9014",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-9014.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:pgadmin:pgadmin:*:*:*:*:*:postgresql:*:*",
                "matchCriteriaId": "829D784F-8B6C-5EA7-8995-F64C3E714842",
                "versionEndExcluding": "8.12",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:postgresql:pgadmin_4:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "A4A99A76-8EC1-5620-8E85-46F06F50A9DC",
                "versionEndExcluding": "8.12",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}