{
  "_annotation": {
    "cve_id": "CVE-2024-27132",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-27132.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:lfprojects:mlflow:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "95DF96D5-91FA-5014-BBEE-131C5112AFA5",
                "versionEndExcluding": "2.10.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}