{
  "_annotation": {
    "cve_id": "CVE-2024-32882",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-32882.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:torchbox:wagtail:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "F3905C2B-0D91-5E3A-B1E1-F8C7DA65006B",
                "versionEndExcluding": "6.0.3",
                "versionStartIncluding": "6.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}