{
  "_annotation": {
    "cve_id": "CVE-2024-45595",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-45595.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:man:d-tale:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "721C5B85-7F81-5BB6-A275-63A4DE30964F",
                "versionEndExcluding": "3.14.1",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}