{
  "_annotation": {
    "cve_id": "CVE-2024-27097",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-27097.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:okfn:ckan:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "F599CE80-36CF-5577-AD90-83ED92DAD187",
                "versionEndExcluding": "2.9.11",
                "versionStartIncluding": "2.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:okfn:ckan:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "B4EE9010-C915-537F-9745-79B9B2DA8BA5",
                "versionEndExcluding": "2.10.4",
                "versionStartIncluding": "2.10.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}