{
  "_annotation": {
    "cve_id": "CVE-2024-26152",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-26152.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:humansignal:label_studio:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "18CD5779-068E-5B1A-BE8A-13A83E0B6944",
                "versionEndExcluding": "1.11.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}