[
  {
  "id": "GHSA-j3f7-7rmc-6wqj",
  "summary": "Improper certificate management in AWS IoT Device SDK v2",
  "details": "The AWS IoT Device SDK v2 for Java, Python, C++ and Node.js appends a user supplied Certificate Authority (CA) to the root CAs instead of overriding it on macOS systems. Additionally, SNI validation is also not enabled when the CA has been \u201coverridden\u201d. TLS handshakes will thus succeed if the peer can be verified either from the user-supplied CA or the system\u2019s default trust-store. Attackers with access to a host\u2019s trust stores or are able to compromise a certificate authority already in the host's trust store (note: the attacker must also be able to spoof DNS in this case) may be able to use this issue to bypass CA pinning. An attacker could then spoof the MQTT broker, and either drop traffic and/or respond with the attacker's data, but they would not be able to forward this data on to the MQTT broker because the attacker would still need the user's private keys to authenticate against the MQTT broker. The 'aws_tls_ctx_options_override_default_trust_store_*' function within the aws-c-io submodule has been updated to address this behavior. This issue affects: Amazon Web Services AWS IoT Device SDK v2 for Java versions prior to 1.5.0 on macOS. Amazon Web Services AWS IoT Device SDK v2 for Python versions prior to 1.7.0 on macOS. Amazon Web Services AWS IoT Device SDK v2 for C++ versions prior to 1.14.0 on macOS. Amazon Web Services AWS IoT Device SDK v2 for Node.js versions prior to 1.6.0 on macOS. Amazon Web Services AWS-C-IO 0.10.7 on macOS.",
  "aliases": [
    "CVE-2021-40831"
  ],
  "modified": "2022-02-15T05:31:22.788787Z",
  "published": "2021-11-24T20:35:03Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-40831"
    },
    {
      "type": "WEB",
      "url": "https://github.com/aws/aws-iot-device-sdk-cpp-v2"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "awsiotsdk",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/awsiotsdk"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.7.0"
            }
          ]
        }
      ],
      "versions": [
        "0.2.4",
        "0.2.9",
        "0.3.0",
        "1.0.2",
        "1.0.3",
        "1.0.5",
        "1.0.6",
        "1.1.0",
        "1.2.0",
        "1.2.1",
        "1.3.0",
        "1.3.1",
        "1.3.2",
        "1.4.0",
        "1.5.0",
        "1.5.1",
        "1.5.10",
        "1.5.11",
        "1.5.12",
        "1.5.13",
        "1.5.14",
        "1.5.15",
        "1.5.16",
        "1.5.17",
        "1.5.18",
        "1.5.2",
        "1.5.3",
        "1.5.4",
        "1.5.5",
        "1.5.6",
        "1.5.7",
        "1.5.8",
        "1.6.0",
        "1.6.1",
        "1.6.2"
      ],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-j3f7-7rmc-6wqj",
        "cvss": {
          "vectorString": "CVSS:3.1/AV:A/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:H",
          "score": 6.3
        },
        "cwes": [
          {
            "description": "The software does not validate, or incorrectly validates, a certificate.",
            "cweId": "CWE-295",
            "name": "Improper Certificate Validation"
          }
        ],
        "source": "https://storage.googleapis.com/ghsa-osv/GHSA-j3f7-7rmc-6wqj.json"
      }
    },
    {
      "package": {
        "name": "aws-iot-device-sdk-v2",
        "ecosystem": "npm",
        "purl": "pkg:npm/aws-iot-device-sdk-v2"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.6.0"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://storage.googleapis.com/ghsa-osv/GHSA-j3f7-7rmc-6wqj.json",
        "ghsa": "https://github.com/advisories/GHSA-j3f7-7rmc-6wqj",
        "cvss": {
          "vectorString": "CVSS:3.1/AV:A/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:H",
          "score": 6.3
        },
        "cwes": [
          {
            "description": "The software does not validate, or incorrectly validates, a certificate.",
            "cweId": "CWE-295",
            "name": "Improper Certificate Validation"
          }
        ]
      }
    }
  ],
  "schema_version": "1.2.0",
  "severity": [
    {"type": "CVSS_V3", "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N"}
                ]

  },
  {
  "id": "PYSEC-2022-10",
  "details": "PIL.ImageMath.eval in Pillow before 9.0.0 allows evaluation of arbitrary expressions, such as ones that use the Python exec method.",
  "aliases": [
    "CVE-2022-22817",
    "GHSA-8vj2-vxx3-667w"
  ],
  "modified": "2022-01-24T23:48:19.853348Z",
  "published": "2022-01-10T14:12:00.853348Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#restrict-builtins-available-to-imagemath-eval"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2022/01/msg00018.html"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-8vj2-vxx3-667w"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "pillow",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/pillow"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "9.0.0"
            }
          ]
        }
      ],
      "versions": [
        "1.0",
        "1.1",
        "1.2",
        "1.3",
        "1.4",
        "1.5",
        "1.6",
        "1.7.0",
        "1.7.1",
        "1.7.2",
        "1.7.3",
        "1.7.4",
        "1.7.5",
        "1.7.6",
        "1.7.7",
        "1.7.8",
        "2.0.0",
        "2.1.0",
        "2.2.0",
        "2.2.1",
        "2.2.2",
        "2.3.0",
        "2.3.1",
        "2.3.2",
        "2.4.0",
        "2.5.0",
        "2.5.1",
        "2.5.2",
        "2.5.3",
        "2.6.0",
        "2.6.1",
        "2.6.2",
        "2.7.0",
        "2.8.0",
        "2.8.1",
        "2.8.2",
        "2.9.0",
        "3.0.0",
        "3.1.0",
        "3.1.0.rc1",
        "3.1.0rc1",
        "3.1.1",
        "3.1.2",
        "3.2.0",
        "3.3.0",
        "3.3.1",
        "3.3.2",
        "3.3.3",
        "3.4.0",
        "3.4.1",
        "3.4.2",
        "4.0.0",
        "4.1.0",
        "4.1.1",
        "4.2.0",
        "4.2.1",
        "4.3.0",
        "5.0.0",
        "5.1.0",
        "5.2.0",
        "5.3.0",
        "5.4.0",
        "5.4.0.dev0",
        "5.4.1",
        "6.0.0",
        "6.1.0",
        "6.2.0",
        "6.2.1",
        "6.2.2",
        "7.0.0",
        "7.1.0",
        "7.1.1",
        "7.1.2",
        "7.2.0",
        "8.0.0",
        "8.0.1",
        "8.1.0",
        "8.1.1",
        "8.1.2",
        "8.2.0",
        "8.3.0",
        "8.3.1",
        "8.3.2",
        "8.4.0"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pillow/PYSEC-2022-10.yaml"
      }
    }
  ],
  "schema_version": "1.2.0",
   "ecosystem_specific": {
        "affected_functions": [
          "eventlet.websocket.WebSocket",
          "eventlet.websocket.WebSocketWSGI"
        ],
        "severity": "HIGH"

      }
}
]